//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UygulamaOdev_31_01_22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ozellik
    {
        public int ID { get; set; }
        public string Icon { get; set; }
        public string Aciklama { get; set; }
        public string ButonRenk { get; set; }
    }
}
