//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UygulamaOdev_31_01_22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int UrunID { get; set; }
        public string UrunAd { get; set; }
        public int KategoriID { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public string UrunAciklama { get; set; }
        public string UrunResim { get; set; }
    
        public virtual Kategori Kategori { get; set; }
    }
}
